'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
class Element{
 constructor(tag='div'){this.tag=tag;this.children=[];this.textContent='';this.value='';this.hidden=false;this.checked=false;this.disabled=false;}
 append(...c){this.children.push(...c);}set textContent(t){this.text=String(t);this.children=[];}get textContent(){return this.text+this.children.map(c=>c.textContent).join('');}
 replaceChildren(...c){this.text='';this.children=c;}setAttribute(k,v){this[k]=v;}set innerHTML(v){throw Error('unsafe HTML');}
 querySelectorAll(q){const all=this.children.flatMap(c=>[c,...c.querySelectorAll('*')]);return q==='*'?all:all.filter(c=>c.tag==='input'&&(q!=='input:checked'||c.checked));}click(){return this.onclick?.();}
}
const ids=[...fs.readFileSync(path.join(__dirname,'../playground/index.html'),'utf8').matchAll(/id="([^"]+)"/g)].map(m=>m[1]);const elements=Object.fromEntries(ids.map(id=>[id,new Element()]));
const sid='a'.repeat(32),other='b'.repeat(32),block=text=>({text,sha256:'abc',total_chars:text.length,truncated:false,source_path:'saved/file'});
const unknown={value:null,known_sum:100,unknown_calls:1};const summary={call_id:'call-001',actor:'assistant',status:'complete',usage:{processed_tokens:null},tool_invocation_count:1,integrity:{ok:true,gaps:[]}};
const idx={session_id:sid,session:{name:'Test',model:'gpt-6-astra',effort:'low',output_mode:'agent'},calls:[summary],totals:Object.fromEntries(['processed_tokens','cached_input_tokens','tool_invocation_count','seconds'].map(k=>[k,unknown])),gaps:[]};
const detail={...summary,session:idx.session,session_id:sid,tool_failed_count:0,source:{record_sha256:'abc'},displayed_reply:block('<script>untrusted</script>'),displayed_questions:{available:true,items:[{question:'Where is your campus?',options:['Strand','Other campus']}]},displayed_reply_relation:'explicit message/call anchor',raw_actor_reply:block('raw answer'),prompt:block('private prompt'),current_input:block('heating?'),tools:[{id:'tool-1',type:'command_execution',status:'completed',input:block('command'),output:block('<img src=x>'),raw:block('raw')}],raw_tool_events:block('events')};
let exportedBlob;let requests=[],failSave=true,notes=[],pendingResolve;
const api=async(route,data)=>{requests.push({route,data});if(route==='/api/sessions')return {sessions:[{id:sid,name:'Test'},{id:other,name:'Other'}]};if(route.endsWith('/reviews')){if(data){if(failSave){failSave=false;throw Error('uncertain response');}notes.push({...data,source:{record_sha256:'abc'}});return {ok:true};}return {reviews:notes,gaps:[]};}if(route.endsWith('/review-export'))return {path:'/private/local-review.md',bytes:100};if(route.endsWith('/review-packet'))return {...idx,messages:[{role:'human',text:'heating?'}],reviews:{reviews:notes},call_detail_routes:{'call-001':'detail'}};if(route.endsWith('/inspect/call-001'))return {...detail,session_id:route.includes(other)?other:sid};if(route.endsWith('/inspect')){if(route.includes(other))return new Promise(r=>pendingResolve=r);return idx;}throw Error(route);};
const node=(tag,text,cls)=>{const e=new Element(tag);if(text!==undefined)e.textContent=text;e.className=cls;return e;};
const context={document:{getElementById:id=>elements[id]},node,renderReply:text=>node('p',text),api,selected:sid,location:{hash:'',pathname:'/'},history:{replaceState(){}},crypto:{randomUUID:()=>require('node:crypto').randomUUID()},toast:()=>{},setTimeout:()=>0,Blob,URL:class extends URL{static createObjectURL(blob){exportedBlob=blob;return "blob:private";}static revokeObjectURL(){}},console};context.window=context;vm.createContext(context);
const settle=async()=>{for(let n=0;n<6;n++)await new Promise(r=>setImmediate(r));};
(async()=>{
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../playground/review.js'),'utf8'),context);
 await elements['show-review'].onclick();await settle();
 assert.equal(elements['chat-view'].hidden,true);assert.equal(elements['review-view'].hidden,false);assert.match(elements['review-detail'].textContent,/<script>untrusted<\/script>/);assert.match(elements['review-totals'].textContent,/1 次未記錄/);assert.equal(requests.filter(r=>r.data).length,0);assert.match(elements['review-detail'].textContent,/Where is your campus/);assert.match(elements['review-detail'].textContent,/explicit message\/call anchor/);detail.tools[0].id='bad\n![tracker](https://bad.test)';await elements['review-md'].onclick();assert.match(elements['review-export-result'].textContent,/local-review.md/);assert.equal(requests.find(r=>r.route.endsWith('/review-export')).data.format,'md');
 elements['review-note'].value='User still asked about heating.';elements['review-rating'].value='problem';elements['review-severity'].value='medium';
 await elements['review-form'].onsubmit({preventDefault(){}});assert.equal(elements['review-note'].value,'User still asked about heating.');await elements['review-form'].onsubmit({preventDefault(){}});
 const writes=requests.filter(r=>r.data&&r.route.endsWith('/reviews'));assert.equal(writes.length,2);assert.equal(writes[0].data.client_id,writes[1].data.client_id);assert.equal(writes[1].data.call_id,'call-001');assert.equal(writes[1].data.reviewer,'human');assert.equal(writes[1].data.expected_source.record_sha256,'abc');assert.equal(elements['review-note'].value,'');assert.match(elements['review-history'].textContent,/User still asked/);
 elements['review-session'].value=other;const slow=elements['review-session'].onchange();await settle();elements['review-session'].value=sid;await elements['review-session'].onchange();await settle();pendingResolve({...idx,session_id:other,session:{...idx.session,name:'WRONG STALE'}});await slow;assert.equal(elements['review-title'].textContent,'Test');
 assert.equal(requests.filter(r=>/\/(message|control)$/.test(r.route)).length,0);elements['show-chat'].onclick();assert.equal(elements['chat-view'].hidden,false);console.log('inspector functional checks passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
