"use strict";
const $=id=>document.getElementById(id);
let catalog=null, current=null, selected=null, lastRevision=null, polling=false, messageIntent=null, createIntent=null, actionIntent=null;
const statuses={ready:"等待開始",paused:"已暫停",running:"對話進行中",ended:"Persona 結束",budget:"到達上限",error:"需要處理",interrupted:"待恢復"};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function toast(text){$("toast").textContent=text;$("toast").hidden=false;setTimeout(()=>$("toast").hidden=true,6000);}
async function api(path,data){const opts={cache:"no-store",headers:{"X-Pea-Client":"persona-lab"}};if(data!==undefined){opts.method="POST";opts.headers["Content-Type"]="application/json";opts.body=JSON.stringify(data);}const r=await fetch(path,opts);const body=await r.json();if(!r.ok)throw Error(body.message||"操作未完成，請查看狀態。");return body;}
function profile(){const p=catalog.personas.find(x=>x.id===$("persona").value);$("profile").replaceChildren(node("p",p.identity),node("small",`${p.language} · 耐心 ${p.patience_turns} 回合 · 原模式 ${p.original_harness}`));}
async function list(){const rows=await api("/api/sessions");$("sessions").replaceChildren();for(const s of rows.sessions){const b=node("button",s.name,"session-card"+(s.id===selected?" active":""));b.append(node("small",`${statuses[s.status]||s.status} · ${s.calls} calls · ${s.tokens===null?"用量未知":s.tokens.toLocaleString()+" tokens"}`));b.onclick=()=>select(s.id);$("sessions").append(b);}}
async function select(id){selected=id;lastRevision=null;current=null;$("title").textContent="正在讀取這段對話…";$("messages").replaceChildren();for(const key of ["step","run","pause","send","message","export"])$(key).disabled=true;try{localStorage.setItem("pea-lab-session",id);}catch(_){}await refresh();await list();}
function render(s){current=s;$("title").textContent=s.name;$("session-label").textContent=`${s.persona_id} · ${s.model} · low`;$("status").textContent=statuses[s.status]||s.status;$("phase").textContent=s.phase_label||"";$("turn").textContent=`${s.persona_turn}/${s.patience_turns}`;$("calls").textContent=`${s.calls}/${s.limits.max_calls}`;$("tokens").textContent=s.tokens===null?"用量待釐清":s.tokens.toLocaleString();$("usage-bar").style.width=`${Math.min(100,100*(s.tokens||0)/s.limits.max_tokens)}%`;$("usage-note").textContent=`上限 ${s.limits.max_tokens.toLocaleString()} · 回答 ${s.actor_calls.assistant} 次／persona ${s.actor_calls.persona} 次`;
 const blocked=["error","interrupted","ended","budget"].includes(s.status);$("step").disabled=s.busy||blocked;$("run").disabled=s.busy||blocked;$("pause").disabled=!s.busy&&!s.auto;$("export").disabled=false;$("recover").hidden=!(s.pending_call&&!s.busy);$("message").disabled=["error","interrupted","budget"].includes(s.status);$("send").disabled=$("message").disabled;$("banner").hidden=!s.notice;$("banner").textContent=s.notice||"";$("queue-note").textContent=s.pending_count?`${s.pending_count} 則插話已保存，將於目前這則完成後優先回答。`:"插話會保存，於目前這則完成後優先回答。";
 $("criteria").replaceChildren(...s.criteria.map(x=>node("li",x)));$("behavior").replaceChildren(node("p",`情緒：${s.mood} · 尚可 ${Math.max(0,s.patience_turns-s.persona_turn)} 回合`),node("p",`Persona 持有 ${s.held_documents.length} 份文件`));for(const e of s.events.slice(-7))$("behavior").append(node("div",`第 ${e[0]} 回合 · ${e[1]}`,"event"));
 const box=$("messages"), nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<180;box.replaceChildren();for(const m of s.messages){const article=node("article",undefined,`message ${m.role}`);article.append(node("div",m.role==="assistant"?"Codex":m.role==="human"?(m.kind==="amendment"?"你 · 情境變更":"你 · 插話"):m.role==="persona"?s.name:"紀錄","speaker"));if(m.pending)article.firstChild.append(node("small","已保存・排隊中"));article.append(node("div",m.text,"bubble"));box.append(article);}if(s.busy){const pending=node("article",undefined,"message system");pending.append(node("div",s.phase_label+"…","bubble"));box.append(pending);}if(nearBottom||lastRevision===null)box.scrollTop=box.scrollHeight;
}
async function refresh(){if(!selected||polling)return;polling=true;try{const requestedId=selected;const s=await api(`/api/session/${requestedId}`);if(selected!==requestedId)return;if(s.revision!==lastRevision){render(s);lastRevision=s.revision;}}catch(e){toast(e.message);}finally{polling=false;}}
async function action(action){try{const fingerprint=JSON.stringify([selected,action]);if(!actionIntent||actionIntent.fingerprint!==fingerprint)actionIntent={fingerprint,id:crypto.randomUUID()};await api(`/api/session/${selected}/control`,{action,client_id:actionIntent.id});actionIntent=null;await refresh();await list();}catch(e){toast(e.message);}}
$("persona").onchange=profile;$("refresh").onclick=()=>list().catch(e=>toast(e.message));$("step").onclick=()=>action("step");$("run").onclick=()=>action("run");$("pause").onclick=()=>action("pause");$("recover").onclick=()=>action("recover");
$("create").onclick=async()=>{const b=$("create");b.disabled=true;try{const settings={persona_id:$("persona").value,model:$("model").value,max_calls:Number($("max-calls").value),max_tokens:Number($("max-tokens").value),seed:1};const fingerprint=JSON.stringify(settings);if(!createIntent||createIntent.fingerprint!==fingerprint)createIntent={fingerprint,id:crypto.randomUUID()};const s=await api("/api/sessions",{...settings,client_id:createIntent.id});createIntent=null;await select(s.id);}catch(e){toast(e.message);}finally{b.disabled=false;}};
$("composer").onsubmit=async e=>{e.preventDefault();const text=$("message").value;if(!text.trim()||!selected)return;$("send").disabled=true;try{const kind=$("amendment").checked?"amendment":"question";const fingerprint=JSON.stringify([selected,text,kind]);if(!messageIntent||messageIntent.fingerprint!==fingerprint)messageIntent={fingerprint,id:crypto.randomUUID()};await api(`/api/session/${selected}/message`,{text,kind,client_id:messageIntent.id});messageIntent=null;$("message").value="";$("amendment").checked=false;await refresh();}catch(err){toast(err.message);}finally{$("send").disabled=false;}};
$("export").onclick=async()=>{try{const s=await api(`/api/session/${selected}/export`);const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:"application/json"}));const a=node("a");a.href=url;a.download=`PRIVATE-persona-${s.persona_id}-${s.id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}};
async function start(){try{catalog=await api("/api/catalog");$("persona").replaceChildren(...catalog.personas.map(p=>{const o=node("option",`${p.id} · ${p.name}`);o.value=p.id;return o;}));$("model").replaceChildren(...catalog.models.map(m=>{const o=node("option",m);o.value=m;return o;}));profile();$("connection").textContent="本機測試台已連接";await list();let previous=null;try{previous=localStorage.getItem("pea-lab-session");}catch(_){}if(previous)await select(previous);setInterval(refresh,1200);}catch(e){$("connection").textContent="連線未就緒";toast(e.message);}}
start();
