"use strict";
const $=id=>document.getElementById(id);
let catalog=null, current=null, selected=null, lastRevision=null, polling=false, messageIntent=null, createIntent=null, actionIntent=null;
const choiceDrafts=new Map(), choiceIntents=new Map(), choiceSending=new Set(), messageSending=new Set();
const statuses={ready:"等待開始",paused:"已暫停",running:"對話進行中",ended:"Persona 結束",budget:"到達上限",error:"需要處理",interrupted:"待恢復"};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function limitNotice(s){
 if(!s)return "";
 if(Number.isFinite(s.calls)&&Number.isFinite(s.limits?.max_calls)&&s.calls>=s.limits.max_calls)return "這段對話已達執行次數上限。仍可閱讀、匯出紀錄；未送出的草稿會保留。";
 if(Number.isFinite(s.tokens)&&Number.isFinite(s.limits?.max_tokens)&&s.tokens>=s.limits.max_tokens)return "這段對話已用完 token 額度。仍可閱讀、匯出紀錄；未送出的草稿會保留。";
 return "";
}
function canCompose(s){return Boolean(s&&s.id===selected&&s.compatible!==false&&!limitNotice(s)&&!["error","interrupted","budget"].includes(s.status));}
function syncComposer(){const blocked=!canCompose(current);$("message").disabled=blocked;$("amendment").disabled=blocked;$("send").disabled=blocked||messageSending.has(selected);}
function canChoose(s,index,id){return canCompose(s)&&s.id===id&&index===s.messages.length-1&&!s.busy&&!s.pending_count&&!choiceSending.has(`${id}:${index}`);}
function clarificationForm(s,m,index){
 const key=`${s.id}:${index}`, form=node("form",undefined,"clarifications");
 const enabled=canChoose(s,index,s.id);
 if(!choiceDrafts.has(key))choiceDrafts.set(key,{});const draft=choiceDrafts.get(key);
 m.questions.forEach((q,qi)=>{const field=node("fieldset"),legend=node("legend",q.question);field.append(legend);field.disabled=!enabled;
   q.options.forEach((label,oi)=>{const row=node("label",undefined,"choice"),input=node("input");input.type="radio";input.name=`choice-${index}-${qi}`;input.value=String(oi);input.checked=draft[qi]?.option===oi;
    input.onchange=()=>{draft[qi]={...(draft[qi]||{}),option:oi};};row.append(input,node("span",label));field.append(row);});
   const custom=node("input");custom.type="text";custom.maxLength=500;custom.placeholder="也可以自己填寫，或補充細節";custom.setAttribute("aria-label",`${q.question}：自行填寫`);custom.value=draft[qi]?.text||"";custom.oninput=()=>{draft[qi]={...(draft[qi]||{}),text:custom.value};};field.append(custom);form.append(field);
 });
 if(enabled){const button=node("button","送出選擇，繼續討論","primary");button.type="submit";form.append(button,node("small","可以只回答部分問題，也可以在下方直接插話。","fine"));
 form.onsubmit=async event=>{event.preventDefault();if(!canChoose(current,index,s.id)){toast(limitNotice(current)||"請先查看最新對話，再送出選擇。");return;}const parts=m.questions.flatMap((q,qi)=>{const d=draft[qi]||{},v=[Number.isInteger(d.option)?q.options[d.option]:"",(d.text||"").trim()].filter(Boolean);return v.length?[q.question+"\n"+v.join("；")]:[];});if(!parts.length){toast("先選一項或填寫你的想法。");return;}button.disabled=true;choiceSending.add(key);const text=parts.join("\n\n"),fingerprint=JSON.stringify([s.id,text]);let intent=choiceIntents.get(key);if(!intent||intent.fingerprint!==fingerprint){intent={fingerprint,id:crypto.randomUUID()};choiceIntents.set(key,intent);}try{await api(`/api/session/${s.id}/message`,{text,kind:"question",client_id:intent.id});choiceDrafts.delete(key);choiceIntents.delete(key);await refresh();}catch(error){toast(error.message);}finally{choiceSending.delete(key);if(current?.id===selected)render(current);}};
 }return form;
}
function toast(text){$("toast").textContent=text;$("toast").hidden=false;setTimeout(()=>$("toast").hidden=true,6000);}
async function api(path,data){const opts={cache:"no-store",headers:{"X-Pea-Client":"persona-lab"}};if(data!==undefined){opts.method="POST";opts.headers["Content-Type"]="application/json";opts.body=JSON.stringify(data);}const r=await fetch(path,opts);const body=await r.json();if(!r.ok)throw Error(body.message||"操作未完成，請查看狀態。");return body;}
function profile(){const p=catalog.personas.find(x=>x.id===$("persona").value);$("profile").replaceChildren(node("p",p.identity),node("small",`${p.language} · 耐心 ${p.patience_turns} 回合`));}
async function list(){const rows=await api("/api/sessions");$("sessions").replaceChildren();for(const s of rows.sessions){const b=node("button",s.name,"session-card"+(s.id===selected?" active":""));b.append(node("small",`${statuses[s.status]||s.status} · ${s.calls} calls · ${s.tokens===null?"用量未知":s.tokens.toLocaleString()+" tokens"}`));b.onclick=()=>select(s.id);$("sessions").append(b);}}
async function select(id){selected=id;lastRevision=null;current=null;$("title").textContent="正在讀取這段對話…";$("messages").replaceChildren();for(const key of ["step","run","pause","send","message","amendment","export"])$(key).disabled=true;try{localStorage.setItem("pea-lab-session",id);}catch(_){}await refresh();await list();}
function render(s){current=s;$("title").textContent=s.name;$("session-label").textContent=`${s.persona_id} · ${s.model}`;$("status").textContent=statuses[s.status]||s.status;$("phase").textContent=s.phase_label||"";$("turn").textContent=`${s.persona_turn}/${s.patience_turns}`;$("calls").textContent=`${s.calls}/${s.limits.max_calls}`;const knownTokens=Number.isFinite(s.tokens);$("tokens").textContent=knownTokens?s.tokens.toLocaleString():(s.busy||s.pending_call?"計算中":"用量未知");$("usage-bar").hidden=!knownTokens;$("usage-bar").style.width=knownTokens?`${Math.max(0,Math.min(100,100*s.tokens/s.limits.max_tokens))}%`:"";$("usage-note").textContent=`上限 ${s.limits.max_tokens.toLocaleString()} · 回答 ${s.actor_calls.assistant} 次／persona ${s.actor_calls.persona} 次`;
 const capNotice=limitNotice(s),blocked=s.compatible===false||Boolean(capNotice)||["error","interrupted","ended","budget"].includes(s.status);$("step").disabled=s.busy||blocked;$("run").disabled=s.busy||blocked;$("pause").disabled=!s.busy&&!s.auto;$("export").disabled=false;$("recover").hidden=!(s.pending_call&&!s.busy);syncComposer();$("banner").hidden=!(capNotice||s.notice);$("banner").textContent=[capNotice,s.notice].filter(Boolean).join("\n");$("queue-note").textContent=s.pending_count?`${s.pending_count} 則插話已保存，將於目前這則完成後優先回答。`:"插話會保存，於目前這則完成後優先回答。";
 $("criteria").replaceChildren(...s.criteria.map(x=>node("li",x)));$("behavior").replaceChildren(node("p",`情緒：${s.mood} · 尚可 ${Math.max(0,s.patience_turns-s.persona_turn)} 回合`),node("p",`Persona 持有 ${s.held_documents.length} 份文件`));for(const e of s.events.slice(-7))$("behavior").append(node("div",`第 ${e[0]} 回合 · ${e[1]}`,"event"));
 const box=$("messages"), nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<180;box.replaceChildren();s.messages.forEach((m,index)=>{const article=node("article",undefined,`message ${m.role}`);article.append(node("div",m.role==="assistant"?"Codex":m.role==="human"?(m.kind==="amendment"?"你 · 情境變更":"你 · 插話"):m.role==="persona"?s.name:"紀錄","speaker"));if(m.pending)article.firstChild.append(node("small","已保存・排隊中"));article.append(node("div",m.display_text??m.text,"bubble"));if(m.questions?.length)article.append(clarificationForm(s,m,index));box.append(article);});if(s.busy){const pending=node("article",undefined,"message system");pending.append(node("div",s.phase_label+"…","bubble"));box.append(pending);}if(nearBottom||lastRevision===null)box.scrollTop=box.scrollHeight;
}
async function refresh(){if(!selected||polling)return;polling=true;try{const requestedId=selected;const s=await api(`/api/session/${requestedId}`);if(selected!==requestedId)return;if(s.revision!==lastRevision||s.compatible!==current?.compatible){render(s);lastRevision=s.revision;}}catch(e){toast(e.message);}finally{polling=false;}}
async function action(action){if(["step","run"].includes(action)&&(!current||current.id!==selected||current.busy||current.compatible===false||limitNotice(current)||["error","interrupted","ended","budget"].includes(current.status))){if(limitNotice(current))toast(limitNotice(current));return;}try{const id=selected,fingerprint=JSON.stringify([id,action]);if(!actionIntent||actionIntent.fingerprint!==fingerprint)actionIntent={fingerprint,id:crypto.randomUUID()};const intent=actionIntent;await api(`/api/session/${id}/control`,{action,client_id:intent.id});if(actionIntent===intent)actionIntent=null;await refresh();await list();}catch(e){toast(e.message);}}
$("persona").onchange=profile;$("refresh").onclick=()=>list().catch(e=>toast(e.message));$("step").onclick=()=>action("step");$("run").onclick=()=>action("run");$("pause").onclick=()=>action("pause");$("recover").onclick=()=>action("recover");
$("create").onclick=async()=>{const b=$("create");b.disabled=true;try{const settings={persona_id:$("persona").value,model:$("model").value,max_calls:Number($("max-calls").value),max_tokens:Number($("max-tokens").value),seed:1};const fingerprint=JSON.stringify(settings);if(!createIntent||createIntent.fingerprint!==fingerprint)createIntent={fingerprint,id:crypto.randomUUID()};const s=await api("/api/sessions",{...settings,client_id:createIntent.id});createIntent=null;await select(s.id);}catch(e){toast(e.message);}finally{b.disabled=false;}};
$("composer").onsubmit=async e=>{e.preventDefault();const text=$("message").value,id=selected;if(!text.trim()||!canCompose(current)||messageSending.has(id))return;const kind=$("amendment").checked?"amendment":"question";messageSending.add(id);syncComposer();try{const fingerprint=JSON.stringify([id,text,kind]);if(!messageIntent||messageIntent.fingerprint!==fingerprint)messageIntent={fingerprint,id:crypto.randomUUID()};const intent=messageIntent;await api(`/api/session/${id}/message`,{text,kind,client_id:intent.id});if(messageIntent===intent)messageIntent=null;if(selected===id&&$("message").value===text){$("message").value="";$("amendment").checked=false;}await refresh();}catch(err){toast(err.message);}finally{messageSending.delete(id);syncComposer();}};
$("export").onclick=async()=>{try{const s=await api(`/api/session/${selected}/export`);const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:"application/json"}));const a=node("a");a.href=url;a.download=`PRIVATE-persona-${s.persona_id}-${s.id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}};
async function start(){try{catalog=await api("/api/catalog");$("persona").replaceChildren(...catalog.personas.map(p=>{const o=node("option",`${p.id} · ${p.name}`);o.value=p.id;return o;}));$("model").replaceChildren(...catalog.models.map(m=>{const o=node("option",m);o.value=m;return o;}));profile();$("connection").textContent="本機測試台已連接";await list();let previous=null;try{previous=localStorage.getItem("pea-lab-session");}catch(_){}if(previous)await select(previous);setInterval(refresh,1200);}catch(e){$("connection").textContent="連線未就緒";toast(e.message);}}
start();
